experiment_name: 'plane'
checkpoint_path: 'models/plane/checkpoints/model_epoch_0060.pth'
num_instances: 3500
latent_dim: 128
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 1
hyper_hidden_features: 256
